=== The Problem with in-memory architectures circa 2004

---

* Inherited an in-memory Java architecture that didn't fit in 32-bit memory space
** Large static in-memory domain object graph for Financial Services application
** Millions of small `List`, `Set`, `Map` instances created with default sized arrays in memory
* Solution: Roll our own in-memory Java data structures
** Started with memory-efficient `FixedSized` `List`, `Set`, `Map` for small sizes
*** Java 9+ introduced similar memory-efficient immutable collections in JDK
** 64-bit JDK 1.4 release eventually gave some relief
*** Software problem (accessible memory) morphed into hardware problem (available memory)
*** https://www.baeldung.com/jvm-compressed-oops[Compressed OOPS] gave some relief for large heaps <32 gig and eventually <64 gig
** Roll our own memory-efficient mutable `Set` and `Map`
*** `UnifiedSet` not built out of `HashMap` like JDK `HashSet`
*** `UnifiedMap` does not store `Entry` objects and inlines keys and values in single array
** Primitive collections were eventually added to Eclipse Collections for `List`, `Set`, `Bag`, `Stack`, `Map`.
* Fast forward two decades to 2023
** Many memory optimizations are part of the open source https://github.com/eclipse/eclipse-collections[Eclipse Collections] (EC) library
** New EC optimizations possible through issue reporting and open source contributions


link:toc.adoc[â¬†ï¸ TOC] /
link:./01_intro.adoc[â¬…ï¸ Intro] /
link:./02_01_the_problem_today.adoc[âž¡ï¸ The problem today] ðŸ¥·
