=== The problems with in-memory Java architectures circa 2004

---

* Worked on an in-memory Financial Serices Java application that didn't fit in 32-bit memory space
** Problem: Millions of small `List`, `Set`, `Map` instances created with default sized arrays
** *Solution 1*: Roll our own "small size" Java collections
* Software problem (accessible memory) morphed into hardware problem (available memory)
** 64-bit JDK 1.4 release initially gave some relief, but increased total heap size
** https://www.baeldung.com/jvm-compressed-oops[Compressed OOPS] gave some relief for large heaps <32 gig and eventually <64 gig
*** This creates a "sweet spot" threshold with cost of 32-bit rerences (4 bytes) vs. 64-bit references (8 bytes)
** *Solution 2*: Roll our own memory-efficient mutable `Set`, `Map`, `List`
** *Solution 3*: Primitive collections were  added to Eclipse Collections



link:toc.adoc[â¬†ï¸ TOC] /
link:./01_intro.adoc[â¬…ï¸ Intro] /
link:./03_the_problem_today.adoc[âž¡ï¸ The problem today] ðŸ¢
