=== Conference Explorer

---

[width=75%]
[cols="2a,8a"]
|====
| link:../code/comparison/src/main/java/example/nativejava/conferences/immutable/set/Conference.java[Conference Record]
|
[source,java,linenums,highlight=1..8]
----
public record Conference(
    String eventName,
    Country country,
    String city,
    LocalDate startDate, LocalDate endDate,
    Set<SessionType> sessionTypes,
    int trackCount, int sessionCount,
    int speakerCount, int cost)
----
| link:../code/comparison/src/main/java/example/nativejava/conferences/immutable/set/ConferenceExplorer.java[Java Streams]
|
[source,java,linenums,highlight=2..3]
----
public class ConferenceExplorer {
    private Set<Conference> conferences;
    private Set<Country> countries;
----
| link:../code/comparison/src/main/java/example/eclipse/collections/conferences/immutable/set/ConferenceExplorer.java[Eclipse Collections]
|
[source,java,linenums,highlight=2..3]
----
public class ConferenceExplorer {
    private ImmutableSet<Conference> conferences;
    private ImmutableSet<Country> countries;
----
| link:../code/comparison/src/main/java/example/dataframeec/conferences/ConferenceExplorer.java[DataFrame-EC]
|
[source,java,linenums,highlight=2..3]
----
public class ConferenceExplorer {
    private DataFrame conferences;
    private DataFrame countryCodes;
----
|====

* Reads in conferences and countries from two CSV files and filters the data for a specified year
* We gave https://github.com/mehmandarov/java-collection-dataframes[talks at Devnexus 2023 and Devoxx Greece 2023] on the API and tests for Conference Explorer
* This talk focuses on the data structures and data and measuring what occupies memory at scale
* What would it cost to load 1 million conferences into memory? Let's find out!

link:toc.adoc[⬆️ TOC] /
link:./14_exploring_three_libraries.adoc[⬅️ What to Choose? In detail.] /
link:./16_ce_memory_cost_mutable_immutable.adoc[➡️ Conference Explorer - Memory Cost - Mutable vs. Immutable] 🐢
